---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: flight-dev
  labels:
    app: flight-dev
spec:
  replicas: 12
  selector:
    matchLabels:
      app: flight-dev
  template:
    metadata:
      labels:
        app: flight-dev
    spec:
      containers:
        - name: flight-dev
          image: {{.image}}
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flight-dev
spec:
  selector:
    app: flight-dev
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: flight-dev

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flight-dev
            port:
             number: 80